"use client";
import {useState,useTransition} from "react";
import {CheckCircle2,Clock3,CalendarDays,MapPin,CreditCard,Package} from "lucide-react";
import {createDemoBooking,purchaseDemoPackage} from "@/lib/actions/demo";
const SLOTS=["10:00","12:00","16:00","18:00","20:00"];
export function DemoBookingForm({coachId,sessionRate,packageRate,locations}:{coachId:string;sessionRate:number;packageRate:number;locations:string[]}){
 const [pending,startTransition]=useTransition();const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const [time,setTime]=useState(SLOTS[0]);const [location,setLocation]=useState(locations[0]??"نادي رياضي");const [step,setStep]=useState<1|2|3>(1);const [error,setError]=useState<string|null>(null);const [ref,setRef]=useState<string|null>(null);
 const single=sessionRate+10, pkg=packageRate+10;
 function submitSingle(){setError(null);startTransition(async()=>{try{const r=await createDemoBooking({coachId,sessionDate:date,startTime:time,location});setRef(r.reference);setStep(3);}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية");}})}
 function submitPackage(){setError(null);startTransition(async()=>{try{const r=await purchaseDemoPackage(coachId);setRef(r.reference);setStep(3);}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية");}})}
 return <div className="rounded-2xl border border-neutral-800 bg-neutral-900 p-4">
  <div className="mb-4 grid grid-cols-3 gap-2 text-[11px]">{["اختيار الموعد","مراجعة الطلب","تم التأكيد"].map((x,i)=><div key={x} className={`rounded-lg p-2 text-center ${step>i?"bg-emerald-600/20 text-emerald-300":"bg-neutral-800 text-neutral-500"}`}>{i+1}. {x}</div>)}</div>
  {step===1&&<div className="space-y-3"><div className="grid grid-cols-2 gap-2"><label className="text-xs text-neutral-400">التاريخ<input type="date" min={date} value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-700 bg-neutral-800 p-2 text-white"/></label><label className="text-xs text-neutral-400">المكان<select value={location} onChange={e=>setLocation(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-700 bg-neutral-800 p-2 text-white">{locations.map(l=><option key={l}>{l}</option>)}</select></label></div><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-neutral-300"><Clock3 size={14}/> المواعيد المتاحة</div><div className="grid grid-cols-5 gap-2">{SLOTS.map(s=><button key={s} onClick={()=>setTime(s)} className={`rounded-lg border p-2 text-xs ${time===s?"border-emerald-500 bg-emerald-600 text-white":"border-neutral-700 bg-neutral-800 text-neutral-400"}`}>{s}</button>)}</div></div><button onClick={()=>setStep(2)} className="w-full rounded-xl bg-emerald-600 py-3 font-bold">متابعة</button></div>}
  {step===2&&<div className="space-y-3"><div className="rounded-xl bg-neutral-800 p-4 text-sm"><div className="flex justify-between"><span className="text-neutral-400">الحصة</span><span>{sessionRate} ج.م</span></div><div className="mt-2 flex justify-between"><span className="text-neutral-400">رسوم التشغيل</span><span>10 ج.م</span></div><div className="mt-3 flex justify-between border-t border-neutral-700 pt-3 font-bold"><span>الإجمالي</span><span className="text-emerald-400">{single} ج.م</span></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-neutral-400"><span><CalendarDays className="mr-1 inline" size={12}/>{date}</span><span><Clock3 className="mr-1 inline" size={12}/>{time}</span><span><MapPin className="mr-1 inline" size={12}/>{location}</span></div></div><button disabled={pending} onClick={submitSingle} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-3 font-bold"><CreditCard size={16}/>دفع تجريبي — {single} ج.م</button><button disabled={pending} onClick={submitPackage} className="flex w-full items-center justify-center gap-2 rounded-xl border border-emerald-500/30 py-3 font-semibold text-emerald-300"><Package size={16}/>باقة 8 حصص — {pkg} ج.م</button>{error&&<p className="text-sm text-red-400">{error}</p>}</div>}
  {step===3&&<div className="space-y-3 text-center"><CheckCircle2 className="mx-auto text-emerald-400" size={52}/><h3 className="text-xl font-bold">تمت العملية التجريبية</h3><p className="text-sm text-neutral-400">لا توجد أي عملية دفع حقيقية.</p><div className="rounded-lg bg-neutral-800 p-2 font-mono text-xs text-emerald-300">{ref}</div><a href="/demo/athlete" className="block rounded-xl bg-emerald-600 py-3 font-bold">لوحة المتدرب</a></div>}
 </div>
}
