"use client";
import { useState, useTransition } from "react";
import { Save } from "lucide-react";
import { updateCoachProfile } from "@/lib/actions/coach";
export function ProfileForm({initial}:{initial:{headline:string;bio:string;session_rate:number;package_8_rate:number;training_locations:string[];languages:string[]}}){
 const [v,setV]=useState(initial); const [busy,start]=useTransition(); const [ok,setOk]=useState(false); const [error,setError]=useState("");
 const submit=()=>{setOk(false);setError("");start(async()=>{try{await updateCoachProfile({headline:v.headline,bio:v.bio,sessionRate:Number(v.session_rate),packageRate:Number(v.package_8_rate),locations:v.training_locations,languages:v.languages});setOk(true)}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ البيانات")}})};
 return <div className="space-y-4 rounded-[2rem] border border-white/7 bg-[#0b1713] p-5"><label className="block text-xs text-[#8aa097]">العنوان<input value={v.headline} onChange={e=>setV({...v,headline:e.target.value})} className="mt-2 min-h-12 w-full rounded-xl border border-white/8 bg-[#07110e] px-3 text-sm text-white outline-none focus:border-emerald-400/40" /></label><label className="block text-xs text-[#8aa097]">نبذة عنك<textarea value={v.bio} onChange={e=>setV({...v,bio:e.target.value})} className="mt-2 min-h-32 w-full rounded-xl border border-white/8 bg-[#07110e] p-3 text-sm leading-6 text-white outline-none focus:border-emerald-400/40" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs text-[#8aa097]">سعر الجلسة<input type="number" min="1" value={v.session_rate} onChange={e=>setV({...v,session_rate:Number(e.target.value)})} className="mt-2 min-h-12 w-full rounded-xl border border-white/8 bg-[#07110e] px-3 text-sm text-white" /></label><label className="block text-xs text-[#8aa097]">سعر باقة 8 حصص<input type="number" min="1" value={v.package_8_rate} onChange={e=>setV({...v,package_8_rate:Number(e.target.value)})} className="mt-2 min-h-12 w-full rounded-xl border border-white/8 bg-[#07110e] px-3 text-sm text-white" /></label></div><label className="block text-xs text-[#8aa097]">أماكن التدريب<input value={v.training_locations.join("، ")} onChange={e=>setV({...v,training_locations:e.target.value.split("،").map(x=>x.trim()).filter(Boolean)})} className="mt-2 min-h-12 w-full rounded-xl border border-white/8 bg-[#07110e] px-3 text-sm text-white" placeholder="القاهرة، الجيزة" /></label><label className="block text-xs text-[#8aa097]">اللغات<input value={v.languages.join("، ")} onChange={e=>setV({...v,languages:e.target.value.split("،").map(x=>x.trim()).filter(Boolean)})} className="mt-2 min-h-12 w-full rounded-xl border border-white/8 bg-[#07110e] px-3 text-sm text-white" placeholder="العربية، English" /></label>{error&&<p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-200">{error}</p>}{ok&&<p className="rounded-xl bg-emerald-400/10 p-3 text-xs font-bold text-emerald-200">تم حفظ الملف.</p>}<button type="button" disabled={busy} onClick={submit} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-400 text-sm font-black text-[#052117] disabled:opacity-50"><Save size={16}/>{busy?"جاري الحفظ...":"حفظ الملف"}</button></div>
}
