"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, Clock3, MapPin, ShieldCheck } from "lucide-react";
import { createBooking } from "@/lib/actions/bookings";
import type { AvailabilityDay } from "@/lib/demo";

type Props = { coachId: string; sessionRate: number; packageRate: number; locations: string[]; availability: AvailabilityDay[] };
export function BookingForm({ coachId, sessionRate, packageRate, locations, availability }: Props) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [error,setError]=useState<string|null>(null); const [date,setDate]=useState(availability[0]?.date??""); const [time,setTime]=useState(availability[0]?.slots[0]??""); const [location,setLocation]=useState(locations[0]??"");
  const selected=useMemo(()=>availability.find(x=>x.date===date),[availability,date]);
  useEffect(()=>{const d=availability.find(x=>x.date===date)||availability[0];if(!d)return;if(d.date!==date)setDate(d.date);if(!d.slots.includes(time))setTime(d.slots[0]??"");},[availability,date,time]);
  function submit(){setError(null);if(!date||!time||!location){setError("اختاري اليوم والميعاد والمكان");return;}startTransition(async()=>{try{await createBooking({coachId,sessionDate:date,startTime:time,endTime:`${String((Number(time.slice(0,2))+1)%24).padStart(2,"0")}:${time.slice(3,5)}`,location});router.push("/dashboard");}catch(e){setError(e instanceof Error?e.message:"تعذر إرسال الطلب");}})}
  return <div className="rounded-[2rem] border border-neutral-800 bg-neutral-900 p-4"><div className="rounded-2xl bg-amber-400/5 p-3 text-xs leading-5 text-amber-100"><b>الدفع الحقيقي غير مفعّل</b> في النسخة المنشورة حاليًا؛ لذلك الطلب الحقيقي يظل في حالة انتظار الدفع ولا يتحول لتأكيد نهائي بدون دفعة ناجحة.</div>{availability.length===0?<div className="mt-4 rounded-2xl border border-dashed border-neutral-700 p-6 text-center text-sm text-neutral-500">مفيش مواعيد متاحة للمدرب خلال الـ14 يوم الجايين.</div>:<><div className="mt-4"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-neutral-300"><CalendarDays size={14}/>اليوم</div><div className="flex gap-2 overflow-x-auto pb-1">{availability.slice(0,7).map(d=><button type="button" key={d.date} onClick={()=>{setDate(d.date);setTime(d.slots[0]??"")}} className={`min-w-28 min-h-16 rounded-2xl border p-3 text-right ${date===d.date?"border-emerald-500 bg-emerald-600 text-white":"border-neutral-700 bg-neutral-950 text-neutral-400"}`}><div className="text-xs font-extrabold">{d.label}</div><div className="mt-1 text-[10px] opacity-70">{d.slots.length} مواعيد</div></button>)}</div></div><div className="mt-4"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-neutral-300"><Clock3 size={14}/>المواعيد</div><div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{selected?.slots.map(s=><button type="button" key={s} onClick={()=>setTime(s)} className={`min-h-11 rounded-xl border text-sm font-bold ${time===s?"border-emerald-500 bg-emerald-600 text-white":"border-neutral-700 bg-neutral-950 text-neutral-400"}`}>{s}</button>)}</div></div><label className="mt-4 block space-y-1.5 text-xs text-neutral-400">مكان التدريب<select value={location} onChange={e=>setLocation(e.target.value)} className="min-h-11 w-full rounded-xl border border-neutral-700 bg-neutral-950 px-3 text-white">{locations.map(l=><option key={l}>{l}</option>)}</select></label><div className="mt-4 rounded-2xl bg-neutral-950 p-4"><div className="flex items-center gap-2 text-xs text-neutral-500"><MapPin size={13}/>{location}</div><div className="mt-2 flex justify-between text-sm"><span className="text-neutral-500">سعر الحصة</span><span className="font-bold">{sessionRate.toLocaleString("ar-EG")} ج.م</span></div><div className="mt-2 text-[11px] text-neutral-600">باقة 8 حصص: {packageRate.toLocaleString("ar-EG")} ج.م — الشراء الفعلي بعد تفعيل الدفع.</div></div>{error&&<p role="alert" className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button type="button" disabled={pending} onClick={submit} className="mt-4 min-h-12 w-full rounded-xl bg-emerald-600 text-sm font-extrabold disabled:opacity-50">{pending?"جارٍ إرسال الطلب...":"إرسال طلب الحجز"}</button><div className="mt-3 text-center text-[10px] text-neutral-600"><ShieldCheck size={12} className="ml-1 inline"/> الميعاد لا يُعتبر مؤكدًا قبل نجاح الدفع.</div></>}</div>
}
