import { createClient } from "@/lib/supabase/server";
export type DirectoryFilters={sport?:string;location?:string;maxRate?:number;q?:string;available?:boolean};
export type AvailabilityDay={date:string;label:string;slots:string[]};
function dateLabel(ds:string){return new Intl.DateTimeFormat("ar-EG",{timeZone:"Africa/Cairo",weekday:"long",day:"numeric",month:"short"}).format(new Date(`${ds}T12:00:00Z`));}
export async function getSports(){const s=await createClient();const{data,error}=await s.from("sports").select("id,slug,name_ar,name_en,category,icon").eq("is_active",true).order("sort_order");if(error)throw new Error(error.message);return data??[];}
export async function getCoachFilterOptions(){const s=await createClient();const[{data:coaches},{data:sports}]=await Promise.all([s.from("coach_public_catalog").select("training_locations"),s.from("sports").select("slug,name_ar").eq("is_active",true).order("sort_order")]);const set=new Set<string>();for(const c of coaches??[])for(const l of c.training_locations??[])set.add(l);return{sports:sports??[],locations:[...set].sort()};}
async function getTodaySlotCounts(){const s=await createClient();const{data,error}=await s.rpc("get_public_coach_slot_counts");if(error)throw new Error(error.message);return new Map<string,number>((data??[]).map((r:any)=>[r.coach_id,Number(r.today_slots??0)]));}
export async function getVerifiedCoaches(filters:DirectoryFilters={},limit=120){const s=await createClient();const sportRows=filters.sport?((await s.from("sports").select("slug,name_ar").eq("is_active",true)).data??[]):[];const sportMap=new Map<string,string>(sportRows.map((x:any)=>[x.slug,x.name_ar]));const[{data,error},counts]=await Promise.all([s.from("coach_public_catalog").select("id,full_name,avatar_url,bio,sports,session_rate,package_8_rate,training_locations,accepting_bookings,rating,total_reviews,experience_years,headline,languages").order("rating",{ascending:false}).limit(limit),getTodaySlotCounts()]);if(error)throw new Error(error.message);return(data??[]).map((c:any)=>({...c,available_today_slots:counts.get(c.id)??0})).filter((c:any)=>{const q=filters.q?.trim().toLowerCase(),sv=filters.sport?.trim().toLowerCase(),lv=filters.location;if(q){const hay=[c.full_name,c.headline,c.bio,...(c.sports??[])].filter(Boolean).join(" ").toLowerCase();if(!hay.includes(q))return false;}if(sv){const names=(c.sports??[]).map((x:string)=>x.toLowerCase());const target=(sportMap.get(sv)??sv).toLowerCase();if(!names.some((n:string)=>n.includes(target)))return false;}if(lv&&!(c.training_locations??[]).includes(lv))return false;if(filters.maxRate&&Number(c.session_rate)>filters.maxRate)return false;if(filters.available&&Number(c.available_today_slots)<=0)return false;return true;});}
export async function getActivePackageForCoach(coachId:string){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return null;const{data,error}=await s.from("athlete_packages").select("id,remaining_sessions,expires_at,status").eq("athlete_id",user.id).eq("coach_id",coachId).eq("status","active").gt("remaining_sessions",0).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data;}
export async function getCoachById(id:string){const s=await createClient();const{data,error}=await s.from("coach_public_catalog").select("*").eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!data)return null;const{data:reviews,error:re}=await s.from("public_reviews").select("id,coach_id,rating,comment,created_at").eq("coach_id",id).order("created_at",{ascending:false}).limit(8);if(re)throw new Error(re.message);return{...data,reviews:reviews??[]};}
export async function getRealAvailability(coachId:string,days=14):Promise<AvailabilityDay[]>{const s=await createClient();const{data,error}=await s.rpc("get_public_coach_slots",{p_coach_id:coachId,p_days:days});if(error)throw new Error(error.message);const grouped=new Map<string,string[]>();for(const row of data??[]){const d=String((row as any).session_date),t=String((row as any).start_time).slice(0,5),slots=grouped.get(d)??[];slots.push(t);grouped.set(d,slots);}return[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,slots])=>({date,label:dateLabel(date),slots:[...new Set(slots)].sort()}));}
