import { createClient } from "@/lib/supabase/server";import { createAdminClient } from "@/lib/supabase/admin";

export type DirectoryFilters={sport?:string;location?:string;maxRate?:number;q?:string;available?:boolean};
export type AvailabilityDay={date:string;label:string;slots:string[]};

function cairoDateString(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function addDays(ds:string,n:number){const [y,m,d]=ds.split("-").map(Number);const v=new Date(Date.UTC(y,m-1,d));v.setUTCDate(v.getUTCDate()+n);return v.toISOString().slice(0,10);}
function parseTime(v:string){const [h,m]=v.slice(0,5).split(":").map(Number);return h*60+m;}
function formatTime(v:number){const h=Math.floor(v/60)%24,m=v%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}
function cairoLocalTimestamp(date:string,time:string){
  const [y,m,d]=date.split("-").map(Number); const [hh,mm]=time.slice(0,5).split(":").map(Number);
  const naive=Date.UTC(y,m-1,d,hh,mm);
  const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Cairo",timeZoneName:"shortOffset",hour:"2-digit",minute:"2-digit"}).formatToParts(new Date(naive));
  const off=(parts.find(p=>p.type==="timeZoneName")?.value??"GMT+0").replace("GMT","");
  const sign=off.startsWith("-")?-1:1; const raw=off.replace(/^[+-]/,""); const offsetParts=raw.split(":"); const oh=Number(offsetParts[0]??0); const om=Number(offsetParts[1]??0); const offset=(oh*60+om)*sign;
  return naive-offset*60000;
}
function label(ds:string){return new Intl.DateTimeFormat("ar-EG",{timeZone:"Africa/Cairo",weekday:"long",day:"numeric",month:"short"}).format(new Date(`${ds}T00:00:00Z`));}

export async function getSports(){const s=await createClient();const{data,error}=await s.from("sports").select("id,slug,name_ar,name_en,category,icon").eq("is_active",true).order("sort_order");if(error)throw new Error(error.message);return data??[];}
export async function getCoachFilterOptions(){const s=await createClient();const[{data:coaches},{data:sports}]=await Promise.all([s.from("coach_public_catalog").select("training_locations").limit(1000),s.from("sports").select("slug,name_ar").eq("is_active",true).order("sort_order")]);const set=new Set<string>();for(const c of coaches??[])for(const l of c.training_locations??[])set.add(l);return {sports:sports??[],locations:[...set].sort()};}
export async function getVerifiedCoaches(filters:DirectoryFilters={},limit=120){const s=await createClient();const sportRows=filters.sport?((await s.from("sports").select("slug,name_ar").eq("is_active",true)).data??[]):[];const sportMap=new Map<string,string>(sportRows.map((x:any)=>[x.slug,x.name_ar]));let q=s.from("coach_public_catalog").select("id,full_name,avatar_url,bio,sports,session_rate,package_8_rate,training_locations,is_available_today,rating,total_reviews,experience_years,headline,languages");if(filters.maxRate)q=q.lte("session_rate",filters.maxRate);const{data,error}=await q.order("rating",{ascending:false}).limit(limit);if(error)throw new Error(error.message);return (data??[]).filter(c=>{const qv=filters.q?.trim().toLowerCase(),sv=filters.sport?.trim().toLowerCase(),lv=filters.location;if(qv){const hay=[c.full_name,c.headline,c.bio,...(c.sports??[])].filter(Boolean).join(" ").toLowerCase();if(!hay.includes(qv))return false;}if(sv){const names=(c.sports??[]).map((x:string)=>x.toLowerCase());const target=(sportMap.get(sv)??sv).toLowerCase();if(!names.some((n:string)=>n.includes(target)))return false;}if(lv&&!(c.training_locations??[]).includes(lv))return false;if(filters.available&&!c.is_available_today)return false;return true;});}

export async function getActivePackageForCoach(coachId:string){const s=await createClient();const{data:user}=await s.auth.getUser();if(!user.user)return null;const{data,error}=await s.from("athlete_packages").select("id,remaining_sessions,expires_at,status").eq("athlete_id",user.user.id).eq("coach_id",coachId).eq("status","active").gt("remaining_sessions",0).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(error.message);return data;}

export async function getCoachById(id:string){const s=await createClient();const{data,error}=await s.from("coach_public_catalog").select("*").eq("id",id).maybeSingle();if(error)throw new Error(error.message);if(!data)return null;const{data:reviews,error:re}=await s.from("public_reviews").select("id,coach_id,rating,comment,created_at").eq("coach_id",id).order("created_at",{ascending:false}).limit(8);if(re)throw new Error(re.message);return {...data,reviews:reviews??[]};}
export async function getRealAvailability(coachId:string,days=14):Promise<AvailabilityDay[]>{const s=await createClient();const nowIso=new Date().toISOString();const admin=createAdminClient();const[{data:av,error:ae},{data:bookings,error:be},{data:blocked,error:ble},{data:holds,error:he}]=await Promise.all([s.from("coach_availability").select("day_of_week,start_time,end_time").eq("coach_id",coachId).eq("is_active",true),admin.from("bookings").select("session_date,start_time,end_time,status").eq("coach_id",coachId).in("status",["pending","confirmed"]),admin.from("coach_blocked_slots").select("starts_at,ends_at").eq("coach_id",coachId),admin.from("booking_checkout_intents").select("session_date,start_time,end_time,expires_at,status").eq("coach_id",coachId).eq("status","pending").gt("expires_at",nowIso)]);if(ae)throw new Error(ae.message);if(be)throw new Error(be.message);if(ble)throw new Error(ble.message);if(he)throw new Error(he.message);const booked=(bookings??[]).map((b:any)=>({date:b.session_date,start:parseTime(String(b.start_time)),end:parseTime(String(b.end_time))}));const blocks=(blocked??[]).map((b:any)=>({start:new Date(b.starts_at).getTime(),end:new Date(b.ends_at).getTime()}));const held=(holds??[]).map((h:any)=>({date:h.session_date,start:parseTime(String(h.start_time)),end:parseTime(String(h.end_time))}));const start=cairoDateString();const now=parseTime(new Intl.DateTimeFormat("en-GB",{timeZone:"Africa/Cairo",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()));const out:AvailabilityDay[]=[];for(let i=0;i<days;i++){const date=addDays(start,i);const [y,m,d]=date.split("-").map(Number);const dow=new Date(Date.UTC(y,m-1,d)).getUTCDay();const day=(av??[]).filter((x:any)=>Number(x.day_of_week)===dow);const slots=new Set<string>();for(const a of day){const from=parseTime(String(a.start_time)),to=parseTime(String(a.end_time));for(let t=from;t+60<=to;t+=60){const bookedClash=booked.some(b=>b.date===date&&t<b.end&&t+60>b.start);const heldClash=held.some(h=>h.date===date&&t<h.end&&t+60>h.start);const ss=cairoLocalTimestamp(date,formatTime(t)),ee=cairoLocalTimestamp(date,formatTime(t+60));const blockClash=blocks.some(b=>ss<b.end&&ee>b.start);if(!bookedClash&&!heldClash&&!blockClash&&!(date===start&&t<=now))slots.add(formatTime(t));}}if(slots.size)out.push({date,label:label(date),slots:[...slots].sort()});}return out;}


